name: NodeJS with Grunt

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: npm install
      - name: Prisma
        run: npx prisma generate
      - name: Dev server
        run: npm run dev
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}
      - name: Linting
        run: npm run lint
      - name: Production server
        run: npm run start
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}
